services:
  db:
    image: mariadb:lts
      #    command: '--default-authentication-plugin=ed25519'
    restart: always
      #    healthcheck:
      #      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      #      interval: 3s
      #      retries: 5
      #      start_period: 30s
      #secrets:
      #- db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internalnet
    environment:
      # - MARIADB_DATABASE=example
      # - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MARIADB_ROOT_PASSWORD="test"
    expose:
      - 3306
      - 33060

  businesslogic:
    build: ./businesslogic
    restart: always
    secrets:
      - db-password
    ports:
      - 5003:5000
    networks:
      - internalnet
        #    depends_on:
        #      db:
        #        condition: service_healthy

  interfacevis:
    build: ./interfacevis
    restart: always
    ports: 
      - 5002:5000
    networks:
      - interfacenet
      - internalnet

  interfaceapi:
    build: ./interfaceapi
    restart: always
    ports: 
      - 5001:5000
    networks:
      - interfacenet
      - internalnet


volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  internalnet:
  interfacenet:
