version : '3.8'

services:
  db:
    image: mariadb
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internalnet
    environment:
      MARIADB_ROOT_PASSWORD: test
      MARIADB_DATABASE: test_database
      MARIADB_USER: test_user
      MARIADB_PASSWORD: test
    expose:
      - 3306
      - 33060
    ports:
      - 3306:3306
      - 33060:33060

  businesslogic:
    build: ./businesslogic
    restart: always
    secrets:
      - db-password
    ports:
      - 15003:5000
    networks:
      - internalnet

  interfacevis:
    build: ./interfacevis
    restart: always
    ports: 
      - 15002:5000
    networks:
      - interfacenet
      - internalnet

  interfaceapi:
    build: ./interfaceapi
    restart: always
    ports: 
      - 15001:5000
    networks:
      - interfacenet
      - internalnet

  interfacespot:
    build: ./interfacespot
    restart: always
    ports:
      - 15004:5000
    networks:
      - internalnet

  mlengine:
    build: ./mlengine
    restart: always
    ports:
      - 15005:5000
    networks:
      - internalnet

volumes:
  db-data: 

secrets:
  db-password:
    file: db/password.txt

networks:
  internalnet:
  interfacenet:
