services:
  db:
    image: mariadb:11-jammy
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      interval: 3s
      retries: 5
      start_period: 30s
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - internalnet
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
      - 33060

  businesslogic:
    build:
      context: businesslogic
      target: builder
    restart: always
    secrets:
      - db-password
    ports:
      - 7999:7999
    networks:
      - internalnet
    depends_on:
      db:
        condition: service_healthy

  interfacevis:
    build:
      context: interfacevis
      target: builder
    restart: always
    ports: 
      - 8000:80
    networks:
      - interfacenet
      - internalnet
    depends_on:
      proxy:
        condition: service_healthy

  interfaceapi:
    build:
      context: interfaceapi
      target: builder
    restart: always
    ports: 
      - 8080:80
    networks:
      - interfacenet
      - internalnet
    depends_on:
      proxy:
        condition: service_healthy

  proxy:
    build: proxy
    restart: always
    ports:
      - 8000:8000
      - 8080:8080
    depends_on: 
      - businesslogic
    networks:
      - interfacenet

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  internalnet:
  interfacenet:
